# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='grad_year',
            field=models.IntegerField(),
        ),
    ]
